#!/usr/bin/env ansible-playbook -i hosts --become -c paramiko
---

- name: Ansible Playbook for configuring Pi-Hole on Raspberry Pi
  hosts: webservers
  roles:
    - { role: prereq }
    - { role: pihole }
  remote_user: pi
  become: yes
