---
- name: Install git
  apt:
    name: git
    state: present

- name: 'Set default bash aliases'
  copy:
    src: ./files/etc_profile.d_bash_aliases.sh
    dest: /etc/profile.d/bash_aliases.sh
    mode: '0600'
  tags: admin

- name: Install admin tools (vim, htop, ntop, nmap)
  apt:
    package: "{{ item }}"
    state: present
  with_items:
    - python-apt
    - python-pip
    - vim
    - htop
    - nmap
    - atop
  tags: admin

- name: Install grin (better grep)
  shell: pip install grin
  tags: admin

- name: Install NTP
  apt:
    package: ntp
    state: present
  tags: ntp

- name: Copy over the NTP configuration
  template:
    src: files/ntp.conf
    dest: /etc/ntp.conf
  notify:
    - restart ntp
    - force ntp update
  tags: ntp

- name: Make sure NTP is started up
  service:
    name: ntp
    state: started
    enabled: yes
  tags: ntp
